create table public.invoice_cron_runs (
  id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null default now(),
  cutoff_at timestamptz not null,
  finished_at timestamptz,
  status text not null default 'running'
    check (status in ('running', 'completed', 'partial', 'interrupted', 'failed')),
  trigger_source text not null default 'unknown',
  due_count integer not null default 0,
  processed_count integer not null default 0,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  skipped_count integer not null default 0,
  deferred_count integer not null default 0,
  interrupted_count integer not null default 0,
  error_message text
);

create table public.invoice_cron_run_items (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.invoice_cron_runs (id) on delete cascade,
  owner_user_id uuid not null references public.profiles (id) on delete cascade,
  schedule_id uuid references public.invoice_schedules (id) on delete set null,
  schedule_title text not null,
  scheduled_for timestamptz not null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'sent', 'failed', 'skipped', 'deferred', 'interrupted')),
  reason text,
  invoice_id uuid references public.invoices (id) on delete set null,
  resend_email_id text,
  started_at timestamptz,
  finished_at timestamptz,
  unique (run_id, schedule_id)
);

create table public.invoice_cron_run_reports (
  run_id uuid not null references public.invoice_cron_runs (id) on delete cascade,
  owner_user_id uuid not null references public.profiles (id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'sent', 'failed')),
  sent_at timestamptz,
  error_message text,
  primary key (run_id, owner_user_id)
);

create index invoice_cron_runs_status_started_at_idx
  on public.invoice_cron_runs (status, started_at);
create index invoice_cron_run_items_run_id_idx
  on public.invoice_cron_run_items (run_id);
create index invoice_cron_run_items_owner_user_id_idx
  on public.invoice_cron_run_items (owner_user_id);
create index invoice_cron_run_items_status_idx
  on public.invoice_cron_run_items (status);
create index invoice_cron_run_reports_status_idx
  on public.invoice_cron_run_reports (status);

alter table public.invoice_cron_runs enable row level security;
alter table public.invoice_cron_run_items enable row level security;
alter table public.invoice_cron_run_reports enable row level security;

create policy "invoice_cron_run_items_select_own"
  on public.invoice_cron_run_items
  for select
  using (auth.uid() = owner_user_id);

create policy "invoice_cron_run_reports_select_own"
  on public.invoice_cron_run_reports
  for select
  using (auth.uid() = owner_user_id);

create or replace function public.finalize_invoice_cron_run(
  p_run_id uuid,
  p_status text,
  p_error_message text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_status not in ('completed', 'partial', 'interrupted', 'failed') then
    raise exception 'Invalid final cron status: %', p_status;
  end if;

  update public.invoice_cron_runs run
     set finished_at = now(),
         status = p_status,
         processed_count = counts.processed_count,
         sent_count = counts.sent_count,
         failed_count = counts.failed_count,
         skipped_count = counts.skipped_count,
         deferred_count = counts.deferred_count,
         interrupted_count = counts.interrupted_count,
         error_message = p_error_message
    from (
      select
        count(*) filter (where status in ('sent', 'failed', 'skipped'))::integer as processed_count,
        count(*) filter (where status = 'sent')::integer as sent_count,
        count(*) filter (where status = 'failed')::integer as failed_count,
        count(*) filter (where status = 'skipped')::integer as skipped_count,
        count(*) filter (where status = 'deferred')::integer as deferred_count,
        count(*) filter (where status = 'interrupted')::integer as interrupted_count
      from public.invoice_cron_run_items
      where run_id = p_run_id
    ) counts
   where run.id = p_run_id;
end;
$$;

revoke all on function public.finalize_invoice_cron_run(uuid, text, text)
  from public, anon, authenticated;
grant execute on function public.finalize_invoice_cron_run(uuid, text, text)
  to service_role;

